### ISSUE TITLE
Homework Feedback - JS1 - Week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [amerdahabi/hyf-homework#3]
Hi, Good Job! 👍 .I saw you have used backpack which is great.

I have one comment for your code.
Task - Housey-Pricey
I think you did not understand the task . You have to calculate the house price for Peter and Julia and then compare with the given house price. 
 Other than this all good.Keep it up 🥇

**Comment by amerdahabi** [comment]
Hi, thanks for your feedback, i think i got it now :)
issues fixed
