### ISSUE TITLE
Homework Feedback JS1-Week2

### ISSUE THREAD

**Issue by ovbm** [amerdahabi/hyf-homework#4]
Hi Amer, 

Here's my feedback for your homework:

Fullname Function
One thing to keep in mind is that with `if ((firstname || lastname) && useFormalName) {` you are checking weather a value of firstname and lastname exist. That is different from checking if the names are empty strings. If you want to check that a string is not empty you have to do either ` firstname !== ""` or ` firstname.length > 0`

Event day 
Good job using the modulo operator. One small detail, if you are using console.log in the function, you don't have to call console.log on the function, as it will just return "undefined".

Good job on the student manager, it works as expected! ⭐️

Hope my feedback was helpful, 

Olivier

**Comment by amerdahabi** [comment]
HI Olivier, thanks for the feedback, sure it was helpful, i fixed it and push it again.

Amer
